---
# tasks file for configure_firewall
- name: Latest security packages installed
  yum:
    name: "{{ security_packages }}"
    state: latest

- name: firewalld enabled and running
  service:
    name: "{{ security_packages }}"
    enabled: true
    state: started

- name: Configure firewalld
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  with_items: "{{ firewall_services }}"
